### ISSUE TITLE
Touch listener consumes click listener

### ISSUE THREAD

**Issue by Potass** [onesky/auto-screenshot-android#10]
Hello,

I have a problem with clicking on screenshot button. As button can be moved the click is nearly always recognized as **touch** event instead of **click** which makes it really hard to take a screenshot. Could you, please, fix the touch listener in *ScreenshotButtonService* class to make it less sensitive to dragging?

Thank you.

**Comment by bretdabaker** [comment]
Fixed in [v0.7.4](https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.4)
