### ISSUE TITLE
Camera Capture button is VERY hard to respond

### ISSUE THREAD

**Issue by tonymontgomery** [onesky/auto-screenshot-android#13]
Units tested:
LG G2
Samsung S3
Kindle Fire Tablet

It is very hard to get auto-screenshot to acknowledge it got a button press from the floating camera button.
I have to grep adb logcat to watch if it responded or not.

I could help out with this if I can get access to code.
This is a great tool and I would love to help contribute.

**Comment by tonymontgomery** [comment]
Here is what I did in ScrenshotButtonService.java to make the button work as desired:

At top of class, I added the following: 

    private final float SCROLL_THRESHOLD = 20;
    private boolean isOnClick;


I mainly changed how the switch case was handled in the 'onTouch' of the listener for the screenshot button.

Here is my full modified code for the onTouchListener:

            this.screenshotButton.setOnTouchListener(new OnTouchListener() {
                int initialX;
                int initialY;
                private float mDownX;
                private float mDownY;
                float initialTouchX;
                float initialTouchY;

            public boolean onTouch(View view, MotionEvent motionEvent) {
                LayoutParams layoutParams = (LayoutParams)ScreenshotButtonService.this.screenshotButton.getLayoutParams();

                if(OneSkyScreenshotHelper.getHelper().isDebug()) {
                    Log.i("OneSkyButton", "MotionEvent = " + motionEvent.toString());
                }

                switch(motionEvent.getAction() & MotionEvent.ACTION_MASK) {

                    case 0: //ACTION_DOWN
                        this.initialX = layoutParams.x;
                        this.initialY = layoutParams.y;
                        this.initialTouchX = motionEvent.getRawX();
                        this.initialTouchY = motionEvent.getRawY();
                        this.mDownX = motionEvent.getX();
                        this.mDownY = motionEvent.getY();
                        isOnClick = true;
                        return true;
                    case 1: //ACTION_UP
                        if (isOnClick){
                            view.performClick();
                        }
                        return true;
                    case 3: //ACTION_CANCEL
                        isOnClick = false;
                        ScreenshotButtonService.this.resetButtonPosition(layoutParams.x, layoutParams.y);
                        return true;
                    case 2: //ACTION_MOVE
                        if ((Math.abs(this.mDownX - motionEvent.getX()) > SCROLL_THRESHOLD || Math.abs(this.mDownY - motionEvent.getY()) > SCROLL_THRESHOLD)){
                            isOnClick = false;
                            layoutParams.x = this.initialX + (int)(motionEvent.getRawX() - this.initialTouchX);
                            layoutParams.y = this.initialY + (int)(motionEvent.getRawY() - this.initialTouchY);
                            ScreenshotButtonService.this.windowManager.updateViewLayout(ScreenshotButtonService.this.screenshotButton, layoutParams);
                            return true;
                        }
                    default:
                        return false;

                }
            }
        });


Hope it helps!

-Tony

**Comment by tonymontgomery** [comment]
Related to: https://github.com/onesky/auto-screenshot-android/issues/10

**Comment by bretdabaker** [comment]
Fixed with a different approach in [v0.7.4](https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.4)

**Comment by bretdabaker** [comment]
Please close the issue if it fixes your problem

**Comment by tonymontgomery** [comment]
Fixed in v0.7.4.
Thanks for addressing issue in such a speedy manner!
