### ISSUE TITLE
Android Studio 2.0.0 InstantRun breaks StringUtils.java

### ISSUE THREAD

**Issue by oguzbabaoglu** [onesky/auto-screenshot-android#14]
The "instant run" feature in Android Studio 2.0.0 adds an extra field of type `com.android.tools.fd.runtime.IncrementalChange` to resource classes.

See this issue for details: https://code.google.com/p/android/issues/detail?id=204714

This breaks line `190` in `com.oneskyapp.screenshot.utils.StringUtils.java`
```java
int id = (Integer) fields[i].get(arrayClass);
```
The field in this case is not of type `Integer` (and can be null as well)

It needs an `instanceof` check or maybe an extra pair of `catch/log`

**Comment by bretdabaker** [comment]
We are looking into the issue, will keep you updated.

**Comment by oguzbabaoglu** [comment]
Thanks for the update.
Are there any plans on moving the source to this repository?
It would allow contributions with PR, possibly resolving issues faster.

**Comment by bretdabaker** [comment]
Fixed in [v0.7.5](https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.5)
