### ISSUE TITLE
Library fails to find strings in separate files

### ISSUE THREAD

**Issue by gilbert-jolly** [onesky/auto-screenshot-android#15]
Our app has strings separated into many files.  e.g. 

values/strings_shared.xml
values/strings_widgets.xml

When the screenshot button is pressed, on a 5.0 device a message is displayed indicating that no strings could be found

**Comment by bretdabaker** [comment]
The SDK checks all strings available at runtime instead of loading the files directly. If you are using Android Studio 2.0, it might be related to https://github.com/onesky/auto-screenshot-android/issues/14 instead of separate files.

Will investigate and fix the problem soon.

**Comment by bretdabaker** [comment]
We have fix string detection bug in [v0.7.5](https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.5), please see if it fixes the problem.

**Comment by gilbert-jolly** [comment]
Great, looks like the issue of string detection is fixed.

I've encountered a seperate upload issue, which ill add shortly
