### ISSUE TITLE
A ways to make a screenshot when button is obscured

### ISSUE THREAD

**Issue by scana** [onesky/auto-screenshot-android#4]
I've noticed that it is impossible to get the screenshot whenever I display a full screen dialog or dialog big enough to cover the screenshot button.
How about implementing some kind of naive shake detector? Imo, it could be really useful :)

**Comment by bretdabaker** [comment]
Thanks for your suggestion, will see how I can improve the way to trigger the screenshot.

**Comment by bretdabaker** [comment]
Most dialogs have their own windows but the screenshot button can only capture current activity's window, so it won't work.

You can still manually capture dialogs, try ```OneSkyScreenshotHelper.getHelper().capture(getDialog().getRootView);```

**Comment by bretdabaker** [comment]
[v0.7.1](https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.1): Button now sits on top of all windows; Dialog and popup menu will be captured as well.

**Comment by scana** [comment]
Wow, thank you for that feature!
